version: '2'
services:
  bench:
    build: ./bench
    image: mofumofuchan/mlucon-proto-bench
    command: ["-t", "http://image/"]
  image:
    build: ./image
    image: mofumofuchan/mlucon-proto-image
    ports:
      - "80:80"
    privileged: true
